#!/bin/sh
# Run precommit code into docker container 
# docker-compose installed is required.

has_hook_script () {
  [ -f package.json ] && cat package.json | grep -q "\"$1\"[[:space:]]*:"
}
cd "."
# Check if precommit script is defined, skip if not
has_hook_script precommit || exit 0

# Add common path where Node can be found
# export PATH="$PATH:/usr/local/bin:/usr/local"

# Export Git hook params
export GIT_PARAMS="$*"

# Run npm script
echo
docker-compose run --rm node sh -c 'npm run -s precommit' || {
  exit 1
}
